[phases.setup]
packages = ["php81", "composer", "php81Extensions.pdo_mysql", "nodejs", "npm"]

[phases.install]
commands = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "npm install",
  "npm run build"
]

[phases.build]
commands = [
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.start]
cmd = ["sh", "-c", "PORT=8080 php artisan serve --host=0.0.0.0 --port=$PORT"]
